model:
  arch: minigpt_v2
  model_type: pretrain
  max_txt_len: 160
  end_sym: "</s>"
  llama_model: "/data/kiriti/MiniGPT-4/llama_weights/Llama-2-7b-chat-hf"
  ckpt: "/data/kiriti/MiniGPT-4/checkpoints/checkpoint_stage2.pth"
  use_grad_checkpoint: true
  low_resource: true
  chat_template: true
  lora_r: 16
  lora_alpha: 32
  lora_dropout: 0.05

datasets:
  strawberry_diagnostic:
    data_type: images
    build_info:
      annotations:
        train:
          storage: "/data/kiriti/MiniGPT-4/plant_diagnostic/datasets/stage2_train_7class_balanced.json"
      images:
        train: "/data/kiriti/MiniGPT-4/plant_diagnostic/data/train_aug"
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 448
      eval:
        name: "blip2_image_eval"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"
      eval:
        name: "blip_caption"
    batch_size: 2

run:
  task: image_text_pretrain
  output_dir: "/data/kiriti/MiniGPT-4/output/strawberry_chat"
  iters_per_epoch: 2000
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 3e-4
  min_lr: 1e-6
  warmup_lr: 1e-7
  warmup_steps_ratio: 0.1

  weight_decay: 0.05
  max_epoch: 8  # 5 epochs head-only + 3 epochs unfrozen
  num_workers: 8
  seed: 42

  # P1 Baseline: Start with head-only training
  batch_size_train: 4
  accumulation_steps: 4
  amp: true
  max_grad_norm: 1.0

  # Distributed training
  distributed: true
  dist_url: "env://"
  device: "cuda"

  # Logging
  wandb_log: false
  job_name: "strawberry_chat_p1"
  resume_ckpt_path: null
  evaluate: true
  train_splits: ["train"]
  val_splits: ["val"]
  max_val_steps: 50
  auto_val_split_ratio: 0.1
